services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:latest
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    #command: '--default-authentication-plugin=mysql_native_password'

    volumes:
      - /home/jukka/wordpress/db_data:/var/lib/mysql
    restart: always
    #expose:
    #  - 3306
    #  - 33060
    ports:
      - 3306:3306
      - 33060:33060
    environment: 
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
  wordpress:
    image: wordpress:latest
    volumes:
      - /home/jukka/wordpress/wp_data:/var/www/html
      - /home/jukka/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 9000:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    restart: always
volumes:
  db_data: 
  wp_data: 