version: '3'
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /home/jukka/homarr/configs:/app/data/configs
      - /home/jukka/homarr/icons:/app/public/icons
      - /home/jukka/homarr/backgrounds:/app/public/backgrounds
      - /home/jukka/homarr/data:/data
    ports:
      - '7575:7575'
